# Dataset Parameters
dataset: "shapes"
n_bits: 1

# Model Parameters
model: "YourModel"
use_cuda: True
save_model_path: null  # If null, the model is not saved

# Custom Model Parameters (you add them as you need, all other parameters in this file must be added)
n_blocks: 8

# Training Parameters
batch_size: 32
num_iters: 5000
lr: 5e-4
clip_grad: 5
eval_every: 500
generate_every: 1000
eval_num_gen: 8
final_num_gen: 100

# Logging parameters
experiment_name: "YourModel, binary shapes 1"

############  Neptune Parameters ############
log_neptune: True
neptune_proj_name: "Add project name from your Neptune account here"
neptune_tags: ["YourModel","shapes"]
api_token: "Add Neptune's API token here"

############  Tensorboard Parameters ############
log_tensorboard: False  # Not yet implemented

############  tqdm and manual logging Parameters ############
log_tqdm: True
log_file: False